# Generated by Django 3.2.16 on 2022-12-21 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorname', models.CharField(max_length=200)),
                ('Nachname', models.CharField(max_length=200)),
                ('Geburtsdatum', models.DateField(default=None, null=True)),
                ('SZVS', models.FloatField()),
                ('Kinder', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vertragstabelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vertragsart', models.CharField(max_length=200)),
                ('Gehaltstufe', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vordienstzeiten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dienstjahre', models.IntegerField()),
                ('Wo', models.CharField(max_length=200)),
                ('Von', models.DateField()),
                ('Bis', models.DateField()),
                ('Anstellungsart', models.CharField(max_length=200)),
                ('MitarbeiterID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personaldaten.mitarbeiter')),
            ],
        ),
        migrations.CreateModel(
            name='Kinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorname', models.CharField(max_length=200)),
                ('Nachname', models.CharField(max_length=200)),
                ('Geburtsdatum', models.DateField(default=None, null=True)),
                ('SZVS', models.FloatField()),
                ('Familienbonus', models.BooleanField()),
                ('Mitarbeiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personaldaten.mitarbeiter')),
            ],
        ),
    ]
