# Generated by Django 3.2.16 on 2022-12-27 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personaldaten', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vordienstzeiten',
            name='Bis',
        ),
        migrations.RemoveField(
            model_name='vordienstzeiten',
            name='MitarbeiterID',
        ),
        migrations.RemoveField(
            model_name='vordienstzeiten',
            name='Von',
        ),
        migrations.AddField(
            model_name='vordienstzeiten',
            name='MitarbeiterNR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personaldaten.mitarbeiter'),
        ),
        migrations.AlterField(
            model_name='vertragstabelle',
            name='Gehaltstufe',
            field=models.CharField(max_length=2),
        ),
    ]
